package testsuite;
import org.testng.annotations.Test;
import PageObjects.*;
import utilities.PageObjectBase;
import org.openqa.selenium.support.PageFactory;
import utilities.Configurations;
import org.w3c.dom.Document;
import org.w3c.dom.NodeList;
import java.util.HashMap;
import org.testng.annotations.AfterTest;
import org.testng.annotations.DataProvider;
import utilities.TestReport;
import java.io.IOException;
import org.testng.Reporter;
import utilities.DataUtil;


/** Conformiq generated test case
	Enter_Login_DetailsSend_a_reminderReminder_submit
*/
public class Enter_Login_DetailsSend_a_reminderReminder_submit extends PageObjectBase
{

	public Enter_Login_DetailsSend_a_reminderReminder_submit()
	{
	}

	private TestReport testReport= new TestReport();


	private StringBuilder overallTestData= new StringBuilder();


	@Test(dataProvider="TestData")
	public void test(final String Step_1_URL_FIELD,final String Step_2_username_TEXTBOX_Status,final String Step_2_username_TEXTBOX_Verification,final String Step_2_Login_BUTTON_Status,final String Step_2_Sign_up_for_a_new_account_HYPERLINK_Status,final String Step_2_Empty_username_error_message_LABEL_Status,final String Step_3_username_TEXTBOX,final String Step_5_Enter_your_password_TEXTBOX_Status,final String Step_5_Enter_your_password_TEXTBOX_Verification,final String Step_5_Login_BUTTON_Status,final String Step_5_Keep_me_logged_in_CHECKBOX_Status,final String Step_5_Keep_me_logged_in_CHECKBOX_Verification,final String Step_5_Only_allow_your_session_to_be_used_from_this_IP_address__CHECKBOX_Status,final String Step_5_Only_allow_your_session_to_be_used_from_this_IP_address__CHECKBOX_Verification,final String Step_5_Lost_your_password__HYPERLINK_Status,final String Step_5_Invalid_credentials_error_message_LABEL_Status,final String Step_6_Enter_your_password_TEXTBOX,final String Step_6_Keep_me_logged_in_CHECKBOX,final String Step_6_Only_allow_your_session_to_be_used_from_this_IP_address__CHECKBOX,final String Step_9_Reset_BUTTON_Status,final String Step_9_Save_BUTTON_Status,final String Step_9_ReporterHL_HYPERLINK_Status,final String Step_9_Reporter_DROPDOWN_Status,final String Step_9_Reporter_DROPDOWN_Verification,final String Step_9_Assigned_To_DROPDOWN_Status,final String Step_9_Assigned_To_DROPDOWN_Verification,final String Step_9_Monitored_By_DROPDOWN_Status,final String Step_9_Monitored_By_DROPDOWN_Verification,final String Step_9_Note_By_DROPDOWN_Status,final String Step_9_Note_By_DROPDOWN_Verification,final String Step_9_Priority_DROPDOWN_Status,final String Step_9_Priority_DROPDOWN_Verification,final String Step_9_Severity_DROPDOWN_Status,final String Step_9_Severity_DROPDOWN_Verification,final String Step_9_View_Status_DROPDOWN_Status,final String Step_9_View_Status_DROPDOWN_Verification,final String Step_9_Show_Sticky_Issues_DROPDOWN_Status,final String Step_9_Show_Sticky_Issues_DROPDOWN_Verification,final String Step_9_Assigned_To_HL_HYPERLINK_Status,final String Step_9_Monitored_By_HL_HYPERLINK_Status,final String Step_9_Note_By_HL_HYPERLINK_Status,final String Step_9_Priority_HL_HYPERLINK_Status,final String Step_9_Severity_HL_HYPERLINK_Status,final String Step_9_View_Status_HL_HYPERLINK_Status,final String Step_9_Show_Sticky_Issues_HL_HYPERLINK_Status,final String Step_9_Category_HL_HYPERLINK_Status,final String Step_9_Category_DROPDOWN_Status,final String Step_9_Category_DROPDOWN_Verification,final String Step_9_Hide_Status_DROPDOWN_Status,final String Step_9_Hide_Status_DROPDOWN_Verification,final String Step_9_Status_DROPDOWN_Status,final String Step_9_Status_DROPDOWN_Verification,final String Step_9_Resolution_DROPDOWN_Status,final String Step_9_Resolution_DROPDOWN_Verification,final String Step_9_Filter_By_Date_Submitted_HL_HYPERLINK_Status,final String Step_9_Filter_by_Date_Submitted_CHECKBOX_Status,final String Step_9_Filter_by_Date_Submitted_CHECKBOX_Verification,final String Step_9_Submitted_Start_Date_CALENDAR_Status,final String Step_9_Submitted_Start_Date_CALENDAR_Verification,final String Step_9_Submited_End_Date_CALENDAR_Status,final String Step_9_Submited_End_Date_CALENDAR_Verification,final String Step_9_Filter_By_Last_Updated_Date_HL_HYPERLINK_Status,final String Step_9_Filter_by_Last_Updated_Date_CHECKBOX_Status,final String Step_9_Filter_by_Last_Updated_Date_CHECKBOX_Verification,final String Step_9_Updated_Start_Date_CALENDAR_Status,final String Step_9_Updated_Start_Date_CALENDAR_Verification,final String Step_9_Updated_End_Date_CALENDAR_Status,final String Step_9_Updated_End_Date_CALENDAR_Verification,final String Step_9_Hide_Status_HL_HYPERLINK_Status,final String Step_9_Status_HL_HYPERLINK_Status,final String Step_9_Resolution__HL_HYPERLINK_Status,final String Step_9_Profile_DROPDOWN_Status,final String Step_9_Profile_DROPDOWN_Verification,final String Step_9_Platform_DROPDOWN_Status,final String Step_9_Platform_DROPDOWN_Verification,final String Step_9_OS_DROPDOWN_Status,final String Step_9_OS_DROPDOWN_Verification,final String Step_9_OS_Version_DROPDOWN_Status,final String Step_9_OS_Version_DROPDOWN_Verification,final String Step_9_Relationships_DROPDOWN_Status,final String Step_9_Relationships_DROPDOWN_Verification,final String Step_9_Profile_HL_HYPERLINK_Status,final String Step_9_Platform_HL_HYPERLINK_Status,final String Step_9_OS_HL_HYPERLINK_Status,final String Step_9_OS_Version_HL_HYPERLINK_Status,final String Step_9_Relationships_HL_HYPERLINK_Status,final String Step_9_Tags_HL_HYPERLINK_Status,final String Step_9_Tags_TEXTBOX_Status,final String Step_9_Tags_TEXTBOX_Verification,final String Step_9_Show_HL_HYPERLINK_Status,final String Step_9_Show_TEXTBOX_Status,final String Step_9_Show_TEXTBOX_Verification,final String Step_9_Sort_by_HL_HYPERLINK_Status,final String Step_9_Report_FIL_DROPDOWN_Status,final String Step_9_Report_FIL_DROPDOWN_Verification,final String Step_9_Ordered_by_DROPDOWN_Status,final String Step_9_Ordered_by_DROPDOWN_Verification,final String Step_9_Match_Type_HL_HYPERLINK_Status,final String Step_9_Match_Type_DROPDOWN_Status,final String Step_9_Match_Type_DROPDOWN_Verification,final String Step_9_Highlight_changed__hours__HL_HYPERLINK_Status,final String Step_9_Highlight_changed_TEXTBOX_Status,final String Step_9_Highlight_changed_TEXTBOX_Verification,final String Step_9_Relationship_Text_TEXTBOX_Status,final String Step_9_Relationship_Text_TEXTBOX_Verification,final String Step_9_Search_TEXTBOX_Status,final String Step_9_Search_TEXTBOX_Verification,final String Step_9_Apply_Filter_BUTTON_Status,final String Step_9_Print_Reports_btn_BUTTON_Status,final String Step_9_CSV_Export_btn_BUTTON_Status,final String Step_9_Excel_Export_btn_BUTTON_Status,final String Step_9_Summary_btn_BUTTON_Status,final String Step_9_Issue_CB_VI_CHECKBOX_Status,final String Step_9_Issue_CB_VI_CHECKBOX_Verification,final String Step_9_Issue_ID__VI_HYPERLINK_Status,final String Step_9_Issue_Edit_VI_HYPERLINK_Status,final String Step_9_Category_VI_LABEL_Status,final String Step_9_Severity_VI_LABEL_Status,final String Step_9_Status_VI_LABEL_Status,final String Step_9_Updated_VI_LABEL_Status,final String Step_9_Summary_VI_LABEL_Status,final String Step_9_Select_All_VI_CHECKBOX_Status,final String Step_9_Select_All_VI_CHECKBOX_Verification,final String Step_9_Sorted_by_VI_DROPDOWN_Status,final String Step_9_Sorted_by_VI_DROPDOWN_Verification,final String Step_9_Ok_BUTTON_Status,final String Step_11_ID_txt_LABEL_Status,final String Step_11_ID_Value_LABEL_Status,final String Step_11_Project_txt_LABEL_Status,final String Step_11_Project_value_LABEL_Status,final String Step_11_Category_txt_LABEL_Status,final String Step_11_Category_value_LABEL_Status,final String Step_11_View_status_txt_LABEL_Status,final String Step_11_View_status_value_LABEL_Status,final String Step_11_Date_submitted_txt_LABEL_Status,final String Step_11_Date_submitted_value_LABEL_Status,final String Step_11_Last_update_LABEL_Status,final String Step_11_Last_update_value_LABEL_Status,final String Step_11_Reporter_txt_LABEL_Status,final String Step_11_Reporter_value_HYPERLINK_Status,final String Step_11_Priority_txt_LABEL_Status,final String Step_11_Priority_value_LABEL_Status,final String Step_11_Status_txt_LABEL_Status,final String Step_11_Status_value_LABEL_Status,final String Step_11_Platform_txt_LABEL_Status,final String Step_11_Platform_value_LABEL_Status,final String Step_11_Assigned_to_txt_LABEL_Status,final String Step_11_Severity_txt_LABEL_Status,final String Step_11_Severity_value_LABEL_Status,final String Step_11_Resolution_txt_LABEL_Status,final String Step_11_Resolution_value_LABEL_Status,final String Step_11_OS_txt_LABEL_Status,final String Step_11_OS_value_LABEL_Status,final String Step_11_Reporoducability_txt_LABEL_Status,final String Step_11_Reproducibility_value_LABEL_Status,final String Step_11_OS_Version_txt_LABEL_Status,final String Step_11_OS_version_value_LABEL_Status,final String Step_11_Summary_txt_LABEL_Status,final String Step_11_Summary_value_LABEL_Status,final String Step_11_Description_txt_LABEL_Status,final String Step_11_Description_value_LABEL_Status,final String Step_11_Steps_to_reproduce_txt_LABEL_Status,final String Step_11_Steps_to_reproduce_value_LABEL_Status,final String Step_11_Additional_Info_txt_LABEL_Status,final String Step_11_Additional_info_txt_LABEL_Status,final String Step_11_Tags_txt_LABEL_Status,final String Step_11_Tag_1_BUTTON_Status,final String Step_11_Tag_2_BUTTON_Status,final String Step_11_Tag_3_BUTTON_Status,final String Step_11_clear_BUTTON_Status,final String Step_11_Attach_tags_txt_LABEL_Status,final String Step_11_seperated_by_comma_TEXTBOX_Status,final String Step_11_seperated_by_comma_TEXTBOX_Verification,final String Step_11_Tags_DD_option_DROPDOWN_Status,final String Step_11_Tags_DD_option_DROPDOWN_Verification,final String Step_11_Attach_tags_BUTTON_Status,final String Step_11_Edit_btn_BUTTON_Status,final String Step_11_Assign_to_btn_BUTTON_Status,final String Step_11_Assign_DD_DROPDOWN_Status,final String Step_11_Assign_DD_DROPDOWN_Verification,final String Step_11_Change_status_to_BUTTON_Status,final String Step_11_Chenage_status_to_DD_DROPDOWN_Status,final String Step_11_Chenage_status_to_DD_DROPDOWN_Verification,final String Step_11_Moniter_btn_BUTTON_Status,final String Step_11_Stick_btn_BUTTON_Status,final String Step_11_Clone_btn_BUTTON_Status,final String Step_11_Close_btn_BUTTON_Status,final String Step_11_Delete_btn_BUTTON_Status,final String Step_11_Assigned_to_value_HYPERLINK_Status,final String Step_11_Current_issue_DD_DROPDOWN_Status,final String Step_11_Current_issue_DD_DROPDOWN_Verification,final String Step_11_Current_Issue_textbox_TEXTBOX_Status,final String Step_11_Current_Issue_textbox_TEXTBOX_Verification,final String Step_11_Add_btn_Relationships_BUTTON_Status,final String Step_11_User_list_textbox_TEXTBOX_Status,final String Step_11_User_list_textbox_TEXTBOX_Verification,final String Step_11_Add_users_BUTTON_Status,final String Step_11_View_Status_txt_LABEL_Status,final String Step_11_Private_CHECKBOX_Status,final String Step_11_Private_CHECKBOX_Verification,final String Step_11_Note_teatarea_TEXTBOX_Status,final String Step_11_Note_teatarea_TEXTBOX_Verification,final String Step_11_Upload_FIles_HYPERLINK_Status,final String Step_11_Add_Note_btn_BUTTON_Status,final String Step_11_Date_Modefied_LABEL_Status,final String Step_11_Username_HYPERLINK_Status,final String Step_11_Field_LABEL_Status,final String Step_11_Change_LABEL_Status,final String Step_11_Make_public_BUTTON_Status,final String Step_11_Delete_activities_BUTTON_Status,final String Step_11_Edit_activities_BUTTON_Status,final String Step_11_username_hl_HYPERLINK_Status,final String Step_11_issue_id_hl_HYPERLINK_Status,final String Step_11_Activity_Notes_txt_LABEL_Status,final String Step_11_Send_a_reminder_btn_BUTTON_Status,final String Step_11_Jump_to_notes_btn_BUTTON_Status,final String Step_11_Jump_to_history_btn_BUTTON_Status,final String Step_11_Prev__Issue_btn_BUTTON_Status,final String Step_11_Next_issue_btn_BUTTON_Status,final String Step_13_View_Status_LABEL_Status,final String Step_13_Private_CHECKBOX_Status,final String Step_13_Private_CHECKBOX_Verification,final String Step_13_To_LABEL_Status,final String Step_13_user_HYPERLINK_Status,final String Step_13_Reminder_txt_area_TEXTBOX_Status,final String Step_13_Reminder_txt_area_TEXTBOX_Verification,final String Step_13_Send_BUTTON_Status,final String Step_14_Private_CHECKBOX,final String Step_14_Reminder_txt_area_TEXTBOX,final String Step_16_Operation_successful__LABEL_Status,final String Step_16_Proceed_BUTTON_Status) throws Exception

	{

	Launch_URL_Page launch_url_page_init=PageFactory.initElements(driver, Launch_URL_Page.class);

	ManageEditProject_Page manageeditproject_page_init=PageFactory.initElements(driver, ManageEditProject_Page.class);

	Login_Screen_Page login_screen_page_init=PageFactory.initElements(driver, Login_Screen_Page.class);

	Loginpass_Screen_Page loginpass_screen_page_init=PageFactory.initElements(driver, Loginpass_Screen_Page.class);

	Issue_Submit_Page issue_submit_page_init=PageFactory.initElements(driver, Issue_Submit_Page.class);

	Manage_Screen_Page manage_screen_page_init=PageFactory.initElements(driver, Manage_Screen_Page.class);

	DeleteTag_popup_Page deletetag_popup_page_init=PageFactory.initElements(driver, DeleteTag_popup_Page.class);

	Mantis_Home_Page mantis_home_page_init=PageFactory.initElements(driver, Mantis_Home_Page.class);

	Report_Issue_Page report_issue_page_init=PageFactory.initElements(driver, Report_Issue_Page.class);

	Update_Issue_scr_Page update_issue_scr_page_init=PageFactory.initElements(driver, Update_Issue_scr_Page.class);

	View_issue_details_Page view_issue_details_page_init=PageFactory.initElements(driver, View_issue_details_Page.class);

	Edit_Activities_note_Page edit_activities_note_page_init=PageFactory.initElements(driver, Edit_Activities_note_Page.class);

	Delete_Activity_note_Page delete_activity_note_page_init=PageFactory.initElements(driver, Delete_Activity_note_Page.class);

	Send_Reminder_popup_Page send_reminder_popup_page_init=PageFactory.initElements(driver, Send_Reminder_popup_Page.class);

	Send_Reminder_Page send_reminder_page_init=PageFactory.initElements(driver, Send_Reminder_Page.class);

	View_Issues_Page view_issues_page_init=PageFactory.initElements(driver, View_Issues_Page.class);

	Print_Reports_Page print_reports_page_init=PageFactory.initElements(driver, Print_Reports_Page.class);
	testReport.createTesthtmlHeader(overallTestData);

	testReport.createHead(overallTestData);

	testReport.putLogo(overallTestData);

	float ne = (float) 0.0;

	testReport.generateGeneralInfo(overallTestData, "Enter_Login_DetailsSend_a_reminderReminder_submit", "TC_Enter_Login_DetailsSend_a_reminderReminder_submit", "",ne);

	testReport.createStepHeader();

	//External Circumstances


	Reporter.log("Step - 1- Perform Launch URL Action");

	testReport.fillTableStep("Step 1", "Perform Launch URL Action");

	launch_url_page_init.enter_URL(Step_1_URL_FIELD);


	Reporter.log("Step - 2- verify Login Screen screen");

	testReport.fillTableStep("Step 2", "verify Login Screen screen");

	login_screen_page_init.verify_username_Status(Step_2_username_TEXTBOX_Status);

	login_screen_page_init.verify_username(Step_2_username_TEXTBOX_Verification);
	login_screen_page_init.verify_Login_Status(Step_2_Login_BUTTON_Status);

	login_screen_page_init.verify_Sign_up_for_a_new_account_Status(Step_2_Sign_up_for_a_new_account_HYPERLINK_Status);

	login_screen_page_init.verify_Empty_username_error_message_Status(Step_2_Empty_username_error_message_LABEL_Status);

	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_2");

	Reporter.log("Step - 3- Fill User Name form Login Screen screen");

	testReport.fillTableStep("Step 3", "Fill User Name form Login Screen screen");

	login_screen_page_init.set_username(Step_3_username_TEXTBOX);
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_3");

	Reporter.log("Step - 4- click Login button Login Screen screen User Name form");

	testReport.fillTableStep("Step 4", "click Login button Login Screen screen User Name form");

	login_screen_page_init.click_Login();
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_4");

	Reporter.log("Step - 5- verify Loginpass Screen screen");

	testReport.fillTableStep("Step 5", "verify Loginpass Screen screen");

	loginpass_screen_page_init.verify_Enter_your_password_Status(Step_5_Enter_your_password_TEXTBOX_Status);

	loginpass_screen_page_init.verify_Enter_your_password(Step_5_Enter_your_password_TEXTBOX_Verification);
	loginpass_screen_page_init.verify_Login_Status(Step_5_Login_BUTTON_Status);

	loginpass_screen_page_init.verify_Keep_me_logged_in_Status(Step_5_Keep_me_logged_in_CHECKBOX_Status);

	loginpass_screen_page_init.verify_Keep_me_logged_in(Step_5_Keep_me_logged_in_CHECKBOX_Verification);
	loginpass_screen_page_init.verify_Only_allow_your_session_to_be_used_from_this_IP_address__Status(Step_5_Only_allow_your_session_to_be_used_from_this_IP_address__CHECKBOX_Status);

	loginpass_screen_page_init.verify_Only_allow_your_session_to_be_used_from_this_IP_address_(Step_5_Only_allow_your_session_to_be_used_from_this_IP_address__CHECKBOX_Verification);
	loginpass_screen_page_init.verify_Lost_your_password__Status(Step_5_Lost_your_password__HYPERLINK_Status);

	loginpass_screen_page_init.verify_Invalid_credentials_error_message_Status(Step_5_Invalid_credentials_error_message_LABEL_Status);

	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_5");

	Reporter.log("Step - 6- Fill Password form Loginpass Screen screen");

	testReport.fillTableStep("Step 6", "Fill Password form Loginpass Screen screen");

	loginpass_screen_page_init.set_Enter_your_password(Step_6_Enter_your_password_TEXTBOX);
	loginpass_screen_page_init.select_Keep_me_logged_in(Step_6_Keep_me_logged_in_CHECKBOX);
	loginpass_screen_page_init.select_Only_allow_your_session_to_be_used_from_this_IP_address_(Step_6_Only_allow_your_session_to_be_used_from_this_IP_address__CHECKBOX);
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_6");

	Reporter.log("Step - 7- click Login button Loginpass Screen screen Password form");

	testReport.fillTableStep("Step 7", "click Login button Loginpass Screen screen Password form");

	loginpass_screen_page_init.click_Login();
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_7");

	Reporter.log("Step - 8- Select View Issues clickchoice Mantis Home screen Mantis Vertical menubar Sections menu");

	testReport.fillTableStep("Step 8", "Select View Issues clickchoice Mantis Home screen Mantis Vertical menubar Sections menu");

	mantis_home_page_init.click_View_Issues();
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_8");

	Reporter.log("Step - 9- verify View Issues screen");

	testReport.fillTableStep("Step 9", "verify View Issues screen");

	view_issues_page_init.verify_Reset_Status(Step_9_Reset_BUTTON_Status);

	view_issues_page_init.verify_Save_Status(Step_9_Save_BUTTON_Status);

	view_issues_page_init.verify_ReporterHL_Status(Step_9_ReporterHL_HYPERLINK_Status);

	view_issues_page_init.verify_Reporter_Status(Step_9_Reporter_DROPDOWN_Status);

	view_issues_page_init.verify_Reporter(Step_9_Reporter_DROPDOWN_Verification);
	view_issues_page_init.verify_Assigned_To_Status(Step_9_Assigned_To_DROPDOWN_Status);

	view_issues_page_init.verify_Assigned_To(Step_9_Assigned_To_DROPDOWN_Verification);
	view_issues_page_init.verify_Monitored_By_Status(Step_9_Monitored_By_DROPDOWN_Status);

	view_issues_page_init.verify_Monitored_By(Step_9_Monitored_By_DROPDOWN_Verification);
	view_issues_page_init.verify_Note_By_Status(Step_9_Note_By_DROPDOWN_Status);

	view_issues_page_init.verify_Note_By(Step_9_Note_By_DROPDOWN_Verification);
	view_issues_page_init.verify_Priority_Status(Step_9_Priority_DROPDOWN_Status);

	view_issues_page_init.verify_Priority(Step_9_Priority_DROPDOWN_Verification);
	view_issues_page_init.verify_Severity_Status(Step_9_Severity_DROPDOWN_Status);

	view_issues_page_init.verify_Severity(Step_9_Severity_DROPDOWN_Verification);
	view_issues_page_init.verify_View_Status_Status(Step_9_View_Status_DROPDOWN_Status);

	view_issues_page_init.verify_View_Status(Step_9_View_Status_DROPDOWN_Verification);
	view_issues_page_init.verify_Show_Sticky_Issues_Status(Step_9_Show_Sticky_Issues_DROPDOWN_Status);

	view_issues_page_init.verify_Show_Sticky_Issues(Step_9_Show_Sticky_Issues_DROPDOWN_Verification);
	view_issues_page_init.verify_Assigned_To_HL_Status(Step_9_Assigned_To_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Monitored_By_HL_Status(Step_9_Monitored_By_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Note_By_HL_Status(Step_9_Note_By_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Priority_HL_Status(Step_9_Priority_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Severity_HL_Status(Step_9_Severity_HL_HYPERLINK_Status);

	view_issues_page_init.verify_View_Status_HL_Status(Step_9_View_Status_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Show_Sticky_Issues_HL_Status(Step_9_Show_Sticky_Issues_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Category_HL_Status(Step_9_Category_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Category_Status(Step_9_Category_DROPDOWN_Status);

	view_issues_page_init.verify_Category(Step_9_Category_DROPDOWN_Verification);
	view_issues_page_init.verify_Hide_Status_Status(Step_9_Hide_Status_DROPDOWN_Status);

	view_issues_page_init.verify_Hide_Status(Step_9_Hide_Status_DROPDOWN_Verification);
	view_issues_page_init.verify_Status_Status(Step_9_Status_DROPDOWN_Status);

	view_issues_page_init.verify_Status(Step_9_Status_DROPDOWN_Verification);
	view_issues_page_init.verify_Resolution_Status(Step_9_Resolution_DROPDOWN_Status);

	view_issues_page_init.verify_Resolution(Step_9_Resolution_DROPDOWN_Verification);
	view_issues_page_init.verify_Filter_By_Date_Submitted_HL_Status(Step_9_Filter_By_Date_Submitted_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Filter_by_Date_Submitted_Status(Step_9_Filter_by_Date_Submitted_CHECKBOX_Status);

	view_issues_page_init.verify_Filter_by_Date_Submitted(Step_9_Filter_by_Date_Submitted_CHECKBOX_Verification);
	view_issues_page_init.verify_Submitted_Start_Date_Status(Step_9_Submitted_Start_Date_CALENDAR_Status);

	view_issues_page_init.verify_Submitted_Start_Date(Step_9_Submitted_Start_Date_CALENDAR_Verification);
	view_issues_page_init.verify_Submited_End_Date_Status(Step_9_Submited_End_Date_CALENDAR_Status);

	view_issues_page_init.verify_Submited_End_Date(Step_9_Submited_End_Date_CALENDAR_Verification);
	view_issues_page_init.verify_Filter_By_Last_Updated_Date_HL_Status(Step_9_Filter_By_Last_Updated_Date_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Filter_by_Last_Updated_Date_Status(Step_9_Filter_by_Last_Updated_Date_CHECKBOX_Status);

	view_issues_page_init.verify_Filter_by_Last_Updated_Date(Step_9_Filter_by_Last_Updated_Date_CHECKBOX_Verification);
	view_issues_page_init.verify_Updated_Start_Date_Status(Step_9_Updated_Start_Date_CALENDAR_Status);

	view_issues_page_init.verify_Updated_Start_Date(Step_9_Updated_Start_Date_CALENDAR_Verification);
	view_issues_page_init.verify_Updated_End_Date_Status(Step_9_Updated_End_Date_CALENDAR_Status);

	view_issues_page_init.verify_Updated_End_Date(Step_9_Updated_End_Date_CALENDAR_Verification);
	view_issues_page_init.verify_Hide_Status_HL_Status(Step_9_Hide_Status_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Status_HL_Status(Step_9_Status_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Resolution__HL_Status(Step_9_Resolution__HL_HYPERLINK_Status);

	view_issues_page_init.verify_Profile_Status(Step_9_Profile_DROPDOWN_Status);

	view_issues_page_init.verify_Profile(Step_9_Profile_DROPDOWN_Verification);
	view_issues_page_init.verify_Platform_Status(Step_9_Platform_DROPDOWN_Status);

	view_issues_page_init.verify_Platform(Step_9_Platform_DROPDOWN_Verification);
	view_issues_page_init.verify_OS_Status(Step_9_OS_DROPDOWN_Status);

	view_issues_page_init.verify_OS(Step_9_OS_DROPDOWN_Verification);
	view_issues_page_init.verify_OS_Version_Status(Step_9_OS_Version_DROPDOWN_Status);

	view_issues_page_init.verify_OS_Version(Step_9_OS_Version_DROPDOWN_Verification);
	view_issues_page_init.verify_Relationships_Status(Step_9_Relationships_DROPDOWN_Status);

	view_issues_page_init.verify_Relationships(Step_9_Relationships_DROPDOWN_Verification);
	view_issues_page_init.verify_Profile_HL_Status(Step_9_Profile_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Platform_HL_Status(Step_9_Platform_HL_HYPERLINK_Status);

	view_issues_page_init.verify_OS_HL_Status(Step_9_OS_HL_HYPERLINK_Status);

	view_issues_page_init.verify_OS_Version_HL_Status(Step_9_OS_Version_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Relationships_HL_Status(Step_9_Relationships_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Tags_HL_Status(Step_9_Tags_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Tags_Status(Step_9_Tags_TEXTBOX_Status);

	view_issues_page_init.verify_Tags(Step_9_Tags_TEXTBOX_Verification);
	view_issues_page_init.verify_Show_HL_Status(Step_9_Show_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Show_Status(Step_9_Show_TEXTBOX_Status);

	view_issues_page_init.verify_Show(Step_9_Show_TEXTBOX_Verification);
	view_issues_page_init.verify_Sort_by_HL_Status(Step_9_Sort_by_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Report_FIL_Status(Step_9_Report_FIL_DROPDOWN_Status);

	view_issues_page_init.verify_Report_FIL(Step_9_Report_FIL_DROPDOWN_Verification);
	view_issues_page_init.verify_Ordered_by_Status(Step_9_Ordered_by_DROPDOWN_Status);

	view_issues_page_init.verify_Ordered_by(Step_9_Ordered_by_DROPDOWN_Verification);
	view_issues_page_init.verify_Match_Type_HL_Status(Step_9_Match_Type_HL_HYPERLINK_Status);

	view_issues_page_init.verify_Match_Type_Status(Step_9_Match_Type_DROPDOWN_Status);

	view_issues_page_init.verify_Match_Type(Step_9_Match_Type_DROPDOWN_Verification);
	view_issues_page_init.verify_Highlight_changed__hours__HL_Status(Step_9_Highlight_changed__hours__HL_HYPERLINK_Status);

	view_issues_page_init.verify_Highlight_changed_Status(Step_9_Highlight_changed_TEXTBOX_Status);

	view_issues_page_init.verify_Highlight_changed(Step_9_Highlight_changed_TEXTBOX_Verification);
	view_issues_page_init.verify_Relationship_Text_Status(Step_9_Relationship_Text_TEXTBOX_Status);

	view_issues_page_init.verify_Relationship_Text(Step_9_Relationship_Text_TEXTBOX_Verification);
	view_issues_page_init.verify_Search_Status(Step_9_Search_TEXTBOX_Status);

	view_issues_page_init.verify_Search(Step_9_Search_TEXTBOX_Verification);
	view_issues_page_init.verify_Apply_Filter_Status(Step_9_Apply_Filter_BUTTON_Status);

	view_issues_page_init.verify_Print_Reports_btn_Status(Step_9_Print_Reports_btn_BUTTON_Status);

	view_issues_page_init.verify_CSV_Export_btn_Status(Step_9_CSV_Export_btn_BUTTON_Status);

	view_issues_page_init.verify_Excel_Export_btn_Status(Step_9_Excel_Export_btn_BUTTON_Status);

	view_issues_page_init.verify_Summary_btn_Status(Step_9_Summary_btn_BUTTON_Status);

	view_issues_page_init.verify_Issue_CB_VI_Status(Step_9_Issue_CB_VI_CHECKBOX_Status);

	view_issues_page_init.verify_Issue_CB_VI(Step_9_Issue_CB_VI_CHECKBOX_Verification);
	view_issues_page_init.verify_Issue_ID__VI_Status(Step_9_Issue_ID__VI_HYPERLINK_Status);

	view_issues_page_init.verify_Issue_Edit_VI_Status(Step_9_Issue_Edit_VI_HYPERLINK_Status);

	view_issues_page_init.verify_Category_VI_Status(Step_9_Category_VI_LABEL_Status);

	view_issues_page_init.verify_Severity_VI_Status(Step_9_Severity_VI_LABEL_Status);

	view_issues_page_init.verify_Status_VI_Status(Step_9_Status_VI_LABEL_Status);

	view_issues_page_init.verify_Updated_VI_Status(Step_9_Updated_VI_LABEL_Status);

	view_issues_page_init.verify_Summary_VI_Status(Step_9_Summary_VI_LABEL_Status);

	view_issues_page_init.verify_Select_All_VI_Status(Step_9_Select_All_VI_CHECKBOX_Status);

	view_issues_page_init.verify_Select_All_VI(Step_9_Select_All_VI_CHECKBOX_Verification);
	view_issues_page_init.verify_Sorted_by_VI_Status(Step_9_Sorted_by_VI_DROPDOWN_Status);

	view_issues_page_init.verify_Sorted_by_VI(Step_9_Sorted_by_VI_DROPDOWN_Verification);
	view_issues_page_init.verify_Ok_Status(Step_9_Ok_BUTTON_Status);

	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_9");

	Reporter.log("Step - 10- click Issue ID  VI hyperlink View Issues screen Viewing  Issues form");

	testReport.fillTableStep("Step 10", "click Issue ID  VI hyperlink View Issues screen Viewing  Issues form");

	view_issues_page_init.click_Issue_ID__VI();
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_10");

	Reporter.log("Step - 11- verify View issue details screen");

	testReport.fillTableStep("Step 11", "verify View issue details screen");

	view_issue_details_page_init.verify_ID_txt_Status(Step_11_ID_txt_LABEL_Status);

	view_issue_details_page_init.verify_ID_Value_Status(Step_11_ID_Value_LABEL_Status);

	view_issue_details_page_init.verify_Project_txt_Status(Step_11_Project_txt_LABEL_Status);

	view_issue_details_page_init.verify_Project_value_Status(Step_11_Project_value_LABEL_Status);

	view_issue_details_page_init.verify_Category_txt_Status(Step_11_Category_txt_LABEL_Status);

	view_issue_details_page_init.verify_Category_value_Status(Step_11_Category_value_LABEL_Status);

	view_issue_details_page_init.verify_View_status_txt_Status(Step_11_View_status_txt_LABEL_Status);

	view_issue_details_page_init.verify_View_status_value_Status(Step_11_View_status_value_LABEL_Status);

	view_issue_details_page_init.verify_Date_submitted_txt_Status(Step_11_Date_submitted_txt_LABEL_Status);

	view_issue_details_page_init.verify_Date_submitted_value_Status(Step_11_Date_submitted_value_LABEL_Status);

	view_issue_details_page_init.verify_Last_update_Status(Step_11_Last_update_LABEL_Status);

	view_issue_details_page_init.verify_Last_update_value_Status(Step_11_Last_update_value_LABEL_Status);

	view_issue_details_page_init.verify_Reporter_txt_Status(Step_11_Reporter_txt_LABEL_Status);

	view_issue_details_page_init.verify_Reporter_value_Status(Step_11_Reporter_value_HYPERLINK_Status);

	view_issue_details_page_init.verify_Priority_txt_Status(Step_11_Priority_txt_LABEL_Status);

	view_issue_details_page_init.verify_Priority_value_Status(Step_11_Priority_value_LABEL_Status);

	view_issue_details_page_init.verify_Status_txt_Status(Step_11_Status_txt_LABEL_Status);

	view_issue_details_page_init.verify_Status_value_Status(Step_11_Status_value_LABEL_Status);

	view_issue_details_page_init.verify_Platform_txt_Status(Step_11_Platform_txt_LABEL_Status);

	view_issue_details_page_init.verify_Platform_value_Status(Step_11_Platform_value_LABEL_Status);

	view_issue_details_page_init.verify_Assigned_to_txt_Status(Step_11_Assigned_to_txt_LABEL_Status);

	view_issue_details_page_init.verify_Severity_txt_Status(Step_11_Severity_txt_LABEL_Status);

	view_issue_details_page_init.verify_Severity_value_Status(Step_11_Severity_value_LABEL_Status);

	view_issue_details_page_init.verify_Resolution_txt_Status(Step_11_Resolution_txt_LABEL_Status);

	view_issue_details_page_init.verify_Resolution_value_Status(Step_11_Resolution_value_LABEL_Status);

	view_issue_details_page_init.verify_OS_txt_Status(Step_11_OS_txt_LABEL_Status);

	view_issue_details_page_init.verify_OS_value_Status(Step_11_OS_value_LABEL_Status);

	view_issue_details_page_init.verify_Reporoducability_txt_Status(Step_11_Reporoducability_txt_LABEL_Status);

	view_issue_details_page_init.verify_Reproducibility_value_Status(Step_11_Reproducibility_value_LABEL_Status);

	view_issue_details_page_init.verify_OS_Version_txt_Status(Step_11_OS_Version_txt_LABEL_Status);

	view_issue_details_page_init.verify_OS_version_value_Status(Step_11_OS_version_value_LABEL_Status);

	view_issue_details_page_init.verify_Summary_txt_Status(Step_11_Summary_txt_LABEL_Status);

	view_issue_details_page_init.verify_Summary_value_Status(Step_11_Summary_value_LABEL_Status);

	view_issue_details_page_init.verify_Description_txt_Status(Step_11_Description_txt_LABEL_Status);

	view_issue_details_page_init.verify_Description_value_Status(Step_11_Description_value_LABEL_Status);

	view_issue_details_page_init.verify_Steps_to_reproduce_txt_Status(Step_11_Steps_to_reproduce_txt_LABEL_Status);

	view_issue_details_page_init.verify_Steps_to_reproduce_value_Status(Step_11_Steps_to_reproduce_value_LABEL_Status);

	view_issue_details_page_init.verify_Additional_Info_txt_Status(Step_11_Additional_Info_txt_LABEL_Status);

	view_issue_details_page_init.verify_Additional_info_txt_Status(Step_11_Additional_info_txt_LABEL_Status);

	view_issue_details_page_init.verify_Tags_txt_Status(Step_11_Tags_txt_LABEL_Status);

	view_issue_details_page_init.verify_Tag_1_Status(Step_11_Tag_1_BUTTON_Status);

	view_issue_details_page_init.verify_Tag_2_Status(Step_11_Tag_2_BUTTON_Status);

	view_issue_details_page_init.verify_Tag_3_Status(Step_11_Tag_3_BUTTON_Status);

	view_issue_details_page_init.verify_clear_Status(Step_11_clear_BUTTON_Status);

	view_issue_details_page_init.verify_Attach_tags_txt_Status(Step_11_Attach_tags_txt_LABEL_Status);

	view_issue_details_page_init.verify_seperated_by_comma_Status(Step_11_seperated_by_comma_TEXTBOX_Status);

	view_issue_details_page_init.verify_seperated_by_comma(Step_11_seperated_by_comma_TEXTBOX_Verification);
	view_issue_details_page_init.verify_Tags_DD_option_Status(Step_11_Tags_DD_option_DROPDOWN_Status);

	view_issue_details_page_init.verify_Tags_DD_option(Step_11_Tags_DD_option_DROPDOWN_Verification);
	view_issue_details_page_init.verify_Attach_tags_Status(Step_11_Attach_tags_BUTTON_Status);

	view_issue_details_page_init.verify_Edit_btn_Status(Step_11_Edit_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Assign_to_btn_Status(Step_11_Assign_to_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Assign_DD_Status(Step_11_Assign_DD_DROPDOWN_Status);

	view_issue_details_page_init.verify_Assign_DD(Step_11_Assign_DD_DROPDOWN_Verification);
	view_issue_details_page_init.verify_Change_status_to_Status(Step_11_Change_status_to_BUTTON_Status);

	view_issue_details_page_init.verify_Chenage_status_to_DD_Status(Step_11_Chenage_status_to_DD_DROPDOWN_Status);

	view_issue_details_page_init.verify_Chenage_status_to_DD(Step_11_Chenage_status_to_DD_DROPDOWN_Verification);
	view_issue_details_page_init.verify_Moniter_btn_Status(Step_11_Moniter_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Stick_btn_Status(Step_11_Stick_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Clone_btn_Status(Step_11_Clone_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Close_btn_Status(Step_11_Close_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Delete_btn_Status(Step_11_Delete_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Assigned_to_value_Status(Step_11_Assigned_to_value_HYPERLINK_Status);

	view_issue_details_page_init.verify_Current_issue_DD_Status(Step_11_Current_issue_DD_DROPDOWN_Status);

	view_issue_details_page_init.verify_Current_issue_DD(Step_11_Current_issue_DD_DROPDOWN_Verification);
	view_issue_details_page_init.verify_Current_Issue_textbox_Status(Step_11_Current_Issue_textbox_TEXTBOX_Status);

	view_issue_details_page_init.verify_Current_Issue_textbox(Step_11_Current_Issue_textbox_TEXTBOX_Verification);
	view_issue_details_page_init.verify_Add_btn_Relationships_Status(Step_11_Add_btn_Relationships_BUTTON_Status);

	view_issue_details_page_init.verify_User_list_textbox_Status(Step_11_User_list_textbox_TEXTBOX_Status);

	view_issue_details_page_init.verify_User_list_textbox(Step_11_User_list_textbox_TEXTBOX_Verification);
	view_issue_details_page_init.verify_Add_users_Status(Step_11_Add_users_BUTTON_Status);

	view_issue_details_page_init.verify_View_Status_txt_Status(Step_11_View_Status_txt_LABEL_Status);

	view_issue_details_page_init.verify_Private_Status(Step_11_Private_CHECKBOX_Status);

	view_issue_details_page_init.verify_Private(Step_11_Private_CHECKBOX_Verification);
	view_issue_details_page_init.verify_Note_teatarea_Status(Step_11_Note_teatarea_TEXTBOX_Status);

	view_issue_details_page_init.verify_Note_teatarea(Step_11_Note_teatarea_TEXTBOX_Verification);
	view_issue_details_page_init.verify_Upload_FIles_Status(Step_11_Upload_FIles_HYPERLINK_Status);

	view_issue_details_page_init.verify_Add_Note_btn_Status(Step_11_Add_Note_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Date_Modefied_Status(Step_11_Date_Modefied_LABEL_Status);

	view_issue_details_page_init.verify_Username_Status(Step_11_Username_HYPERLINK_Status);

	view_issue_details_page_init.verify_Field_Status(Step_11_Field_LABEL_Status);

	view_issue_details_page_init.verify_Change_Status(Step_11_Change_LABEL_Status);

	view_issue_details_page_init.verify_Make_public_Status(Step_11_Make_public_BUTTON_Status);

	view_issue_details_page_init.verify_Delete_activities_Status(Step_11_Delete_activities_BUTTON_Status);

	view_issue_details_page_init.verify_Edit_activities_Status(Step_11_Edit_activities_BUTTON_Status);

	view_issue_details_page_init.verify_username_hl_Status(Step_11_username_hl_HYPERLINK_Status);

	view_issue_details_page_init.verify_issue_id_hl_Status(Step_11_issue_id_hl_HYPERLINK_Status);

	view_issue_details_page_init.verify_Activity_Notes_txt_Status(Step_11_Activity_Notes_txt_LABEL_Status);

	view_issue_details_page_init.verify_Send_a_reminder_btn_Status(Step_11_Send_a_reminder_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Jump_to_notes_btn_Status(Step_11_Jump_to_notes_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Jump_to_history_btn_Status(Step_11_Jump_to_history_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Prev__Issue_btn_Status(Step_11_Prev__Issue_btn_BUTTON_Status);

	view_issue_details_page_init.verify_Next_issue_btn_Status(Step_11_Next_issue_btn_BUTTON_Status);

	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_11");

	Reporter.log("Step - 12- click Send a reminder btn button View issue details screen");

	testReport.fillTableStep("Step 12", "click Send a reminder btn button View issue details screen");

	view_issue_details_page_init.click_Send_a_reminder_btn();
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_12");

	Reporter.log("Step - 13- verify Send Reminder screen");

	testReport.fillTableStep("Step 13", "verify Send Reminder screen");

	send_reminder_page_init.verify_View_Status_Status(Step_13_View_Status_LABEL_Status);

	send_reminder_page_init.verify_Private_Status(Step_13_Private_CHECKBOX_Status);

	send_reminder_page_init.verify_Private(Step_13_Private_CHECKBOX_Verification);
	send_reminder_page_init.verify_To_Status(Step_13_To_LABEL_Status);

	send_reminder_page_init.verify_user_Status(Step_13_user_HYPERLINK_Status);

	send_reminder_page_init.verify_Reminder_txt_area_Status(Step_13_Reminder_txt_area_TEXTBOX_Status);

	send_reminder_page_init.verify_Reminder_txt_area(Step_13_Reminder_txt_area_TEXTBOX_Verification);
	send_reminder_page_init.verify_Send_Status(Step_13_Send_BUTTON_Status);

	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_13");

	Reporter.log("Step - 14- Fill Send Reminder form form Send Reminder screen");

	testReport.fillTableStep("Step 14", "Fill Send Reminder form form Send Reminder screen");

	send_reminder_page_init.select_Private(Step_14_Private_CHECKBOX);
	send_reminder_page_init.set_Reminder_txt_area(Step_14_Reminder_txt_area_TEXTBOX);
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_14");

	Reporter.log("Step - 15- click Send button Send Reminder screen");

	testReport.fillTableStep("Step 15", "click Send button Send Reminder screen");

	send_reminder_page_init.click_Send();
	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_15");

	Reporter.log("Step - 16- verify Send Reminder popup popup");

	testReport.fillTableStep("Step 16", "verify Send Reminder popup popup");

	send_reminder_popup_page_init.verify_Text("[Don't Care]");
	send_reminder_popup_page_init.verify_Operation_successful__Status(Step_16_Operation_successful__LABEL_Status);

	send_reminder_popup_page_init.verify_Proceed_Status(Step_16_Proceed_BUTTON_Status);

	getScreenshot(driver,Configurations.screenshotLocation , "Enter_Login_DetailsSend_a_reminderReminder_submit","Step_16");
	}
	@DataProvider(name = "TestData")
	public Object[][] getData() {
	return DataUtil.getDataFromSpreadSheet("TestData.xlsx", "TCID_3");
}
	@AfterTest
	public void export(){
		testReport.appendtestData(overallTestData);
		testReport.closeStepTable();
		testReport.closeTestHTML(overallTestData);
		driver.close();
		try {
			testReport.writeTestReporthtml(overallTestData, "Enter_Login_DetailsSend_a_reminderReminder_submit");
		} catch (IOException e) {
			e.printStackTrace();
		}
	}
}
